apiVersion: v1
kind: Service
metadata:
  name: kafka-connect
  namespace: kafka
spec:
  ports:
  - port: 8083
  clusterIP: None
  selector:
    app: kafka-connect
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: kafka-connect
  namespace: kafka
spec:
  serviceName: "kafka-connect"
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-connect
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: connect
        image: confluentinc/cp-kafka-connect
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper1-0.zookeeper1.kafka.svc.cluster.local:2181,zookeeper2-0.zookeeper2.kafka.svc.cluster.local:2181,zookeeper3-0.zookeeper3.kafka.svc.cluster.local:2181
        - name: CONNECT_BOOTSTRAP_SERVERS
          value: broker1-0.kafka1.kafka.svc.cluster.local:9092,broker2-0.kafka2.kafka.svc.cluster.local:9092,broker3-0.kafka3.kafka.svc.cluster.local:9092
        - name: CONNECT_REST_PORT
          value: 8083
        - name: CONNECT_GROUP_ID
          value: quickstart-avro
        - name: CONNECT_CONFIG_STORAGE_TOPIC
          value: quickstart-avro-config
        - name: CONNECT_OFFSET_STORAGE_TOPIC
          value: quickstart-avro-offsets
        - name: CONNECT_STATUS_STORAGE_TOPIC
          value: quickstart-avro-status
        - name: CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR
          value: 3
        - name: CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR
          value: 3
        - name: CONNECT_STATUS_STORAGE_REPLICATION_FACTOR
          value: 3
	- name: CONNECT_KEY_CONVERTER
          value: io.confluent.connect.avro.AvroConverter
        - name: CONNECT_VALUE_CONVERTER
          value: io.confluent.connect.avro.AvroConverter
        - name: CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL
          value: "http://registry3-0.schema3.kafka.svc.cluster.local:8081"
        - name: CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL
          value: "http://registry3-0.schema3.kafka.svc.cluster.local:8081"
        - name: CONNECT_INTERNAL_KEY_CONVERTER
          value: "org.apache.kafka.connect.json.JsonConverter"
        - name: CONNECT_INTERNAL_VALUE_CONVERTER
          value: "org.apache.kafka.connect.json.JsonConverter"
        - name: CONNECT_REST_ADVERTISED_HOST_NAME
          value: "localhost"
        - name: CONNECT_LOG4J_ROOT_LOGLEVEL
          value: "DEBUG"
        - name: CONNECT_LOG4J_LOGGERS=org.reflections
          value: "ERROR"
        - name: CONNECT_PLUGIN_PATH
          value: "/usr/share/java,/etc/kafka-connect/jars"
        ports:
        - containerPort: 8083
