apiVersion: v1
kind: Service
metadata:
  name: connect-ui
  namespace: kafka
spec:
  ports:
  - port: 8000
  clusterIP: None
  selector:
    app: connect-ui
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: connect-ui
  namespace: kafka
spec:
  serviceName: "connect-ui"
  replicas: 1
  template:
    metadata:
      labels:
        app: connect-ui
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: connect-ui
        image: landoop/kafka-connect-ui
        env:
        - name: CONNECT_URL
          value: http://connect.distributed.url
        ports:
        - containerPort: 8000
