apiVersion: v1
kind: Service
metadata:
  name: kafka1
  namespace: kafka
spec:
  ports:
  - port: 9092
  clusterIP: None
  selector:
    app: kafka1
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: broker1
  namespace: kafka
spec:
  serviceName: "kafka1"
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka1
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: kafka1
        image: confluentinc/cp-kafka
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper1-0.zookeeper1.kafka.svc.cluster.local:2181,zookeeper2-0.zookeeper2.kafka.svc.cluster.local:2181,zookeeper3-0.zookeeper3.kafka.svc.cluster.local:2181"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://broker1-0.kafka1.kafka.svc.cluster.local:9092
        - name: KAFKA_BROKER_ID
          value: "0"
        ports:
        - containerPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: kafka2
  namespace: kafka
spec:
  ports:
  - port: 9092
  clusterIP: None
  selector:
    app: kafka2
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: broker2
  namespace: kafka
spec:
  serviceName: "kafka2"
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka2
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: kafka2
        image: confluentinc/cp-kafka
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper1-0.zookeeper1.kafka.svc.cluster.local:2181,zookeeper2-0.zookeeper2.kafka.svc.cluster.local:2181,zookeeper3-0.zookeeper3.kafka.svc.cluster.local:2181"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://broker2-0.kafka2.kafka.svc.cluster.local:9092
        - name: KAFKA_BROKER_ID
          value: "1"
        ports:
        - containerPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: kafka3
  namespace: kafka
spec:
  ports:
  - port: 9092
  clusterIP: None
  selector:
    app: kafka3
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: broker3
  namespace: kafka
spec:
  serviceName: "kafka3"
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka3
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: kafka3
        image: confluentinc/cp-kafka
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper1-0.zookeeper1.kafka.svc.cluster.local:2181,zookeeper2-0.zookeeper2.kafka.svc.cluster.local:2181,zookeeper3-0.zookeeper3.kafka.svc.cluster.local:2181"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://broker3-0.kafka3.kafka.svc.cluster.local:9092
        - name: KAFKA_BROKER_ID
          value: "3"
        ports:
        - containerPort: 9092
