apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: kafka
spec:
  ports:
  - port: 3306
  clusterIP: None
  selector:
    app: mysql
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mysql
  namespace: kafka
spec:
  serviceName: "mysql"
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers: 
      - name: mysql
        image: mysql:latest
        env: 
        - name: "MYSQL_ROOT_PASSWORD"
          value: confluent
        - name: "MYSQL_USER"
          value: confluent
        - name: "MYSQL_PASSWORD"
          value: confluent
        - name: "MYSQL_DATABASE"
          value: connect_test
        ports: 
          - containerPort: 3306
