apiVersion: v1
kind: Service
metadata:
  name: schema1
  namespace: kafka
spec:
  ports:
  - port: 8081
  clusterIP: None
  selector:
    app: schema-registry1
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: registry1
  namespace: kafka
spec:
  serviceName: "schema1"
  replicas: 1
  template:
    metadata:
      labels:
        app: schema-registry1
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: schema-registry1
        image: confluentinc/cp-schema-registry
        env:
        - name: SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
          value: zookeeper1-0.zookeeper1.kafka.svc.cluster.local:2181,zookeeper2-0.zookeeper2.kafka.svc.cluster.local:2181,zookeeper3-0.zookeeper3.kafka.svc.cluster.local:2181
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: registry1-0.schema1.kafka.svc.cluster.local
        - name: SCHEMA_REGISTRY_LISTENERS
          value: http://0.0.0.0:8081
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: schema2
  namespace: kafka
spec:
  ports:
  - port: 8081
  clusterIP: None
  selector:
    app: schema-registry2
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: registry2
  namespace: kafka
spec:
  serviceName: "schema2"
  replicas: 1
  template:
    metadata:
      labels:
        app: schema-registry2
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: schema-registry2
        image: confluentinc/cp-schema-registry
        env:
        - name: SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
          value: zookeeper1-0.zookeeper1.kafka.svc.cluster.local:2181,zookeeper2-0.zookeeper2.kafka.svc.cluster.local:2181,zookeeper3-0.zookeeper3.kafka.svc.cluster.local:2181
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: registry2-0.schema2.kafka.svc.cluster.local
        - name: SCHEMA_REGISTRY_LISTENERS
          value: http://0.0.0.0:8081
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: schema3
  namespace: kafka
spec:
  ports:
  - port: 8081
  clusterIP: None
  selector:
    app: schema-registry3
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: registry3
  namespace: kafka
spec:
  serviceName: "schema3"
  replicas: 1
  template:
    metadata:
      labels:
        app: schema-registry3
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: schema-registry3
        image: confluentinc/cp-schema-registry
        env:
        - name: SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
          value: zookeeper1-0.zookeeper1.kafka.svc.cluster.local:2181,zookeeper2-0.zookeeper2.kafka.svc.cluster.local:2181,zookeeper3-0.zookeeper3.kafka.svc.cluster.local:2181
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: registry3-0.schema3.kafka.svc.cluster.local
        - name: SCHEMA_REGISTRY_LISTENERS
          value: http://0.0.0.0:8081
        ports:
        - containerPort: 8081
