apiVersion: v1
kind: Service
metadata:
  name: topics-ui
  namespace: kafka
spec:
  ports:
  - port: 8000
    protocol: TCP
#  clusterIP: None
  selector:
    app: topics-ui
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: topics-ui
  namespace: kafka
spec:
  serviceName: "topics-ui"
  replicas: 1
  template:
    metadata:
      labels:
        app: topics-ui
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: topics-ui
        image: landoop/kafka-topics-ui
        env:
        - name: KAFKA_REST_PROXY_URL
          value: http://rest-0.rest.kafka.svc.cluster.local:8082
        - name: PROXY
          value: "TRUE"
        ports:
        - containerPort: 8000
