apiVersion: v1
kind: Service
metadata:
  name: zoonavigator-web
  namespace: kafka
spec:
  ports:
  - port: 8001
  clusterIP: None
  selector:
    app: zoonavigator-web
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: zoonavigator-web
  namespace: kafka
spec:
  serviceName: "zoonavigator-web"
  replicas: 1
  template:
    metadata:
      labels:
        app: zoonavigator-web
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: zoonavigator-web
        image: elkozmon/zoonavigator-web:latest
        env:
        - name: API_HOST
          value: "zoonavigator-api-0.zoonavigator-api.kafka.svc.cluster.local"
        - name: API_PORT
          value: "9001"
