apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: zookeeper1
  namespace: kafka
spec:
  serviceName: "zookeeper1"
  replicas: 1
  template:
    metadata:
      labels:
        app: zookeeper1
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: zookeeper1
        image: confluentinc/cp-zookeeper
        env:
        - name: ZOOKEEPER_SERVER_ID
          value: "1"
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        - name: ZOOKEEPER_INIT_LIMIT
          value: "5"
        - name: ZOOKEEPER_SYNC_LIMIT
          value: "2"
        - name: ZOOKEEPER_SERVERS
          value: "zookeeper1-0.zookeeper1.kafka.svc.cluster.local:2888:3888;zookeeper2-0.zookeeper2.kafka.svc.cluster.local:2888:3888;zookeeper3-0.zookeeper3.kafka.svc.cluster.local:2888:3888"
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: lead-election
        - containerPort: 3888
          name: zoo-election
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: zookeeper2
  namespace: kafka
spec:
  serviceName: "zookeeper2"
  replicas: 1
  template:
    metadata:
      labels:
        app: zookeeper2
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: zookeeper2
        image: confluentinc/cp-zookeeper
        env:
        - name: ZOOKEEPER_SERVER_ID
          value: "2"
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        - name: ZOOKEEPER_INIT_LIMIT
          value: "5"
        - name: ZOOKEEPER_SYNC_LIMIT
          value: "2"
        - name: ZOOKEEPER_SERVERS
          value: "zookeeper1-0.zookeeper1.kafka.svc.cluster.local:2888:3888;zookeeper2-0.zookeeper2.kafka.svc.cluster.local:2888:3888;zookeeper3-0.zookeeper3.kafka.svc.cluster.local:2888:3888"
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: lead-election
        - containerPort: 3888
          name: zoo-election
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: zookeeper3
  namespace: kafka
spec:
  serviceName: "zookeeper3"
  replicas: 1
  template:
    metadata:
      labels:
        app: zookeeper3
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: zookeeper3
        image: confluentinc/cp-zookeeper
        env:
        - name: ZOOKEEPER_SERVER_ID
          value: "3"
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        - name: ZOOKEEPER_INIT_LIMIT
          value: "5"
        - name: ZOOKEEPER_SYNC_LIMIT
          value: "2"
        - name: ZOOKEEPER_SERVERS
          value: "zookeeper1-0.zookeeper1.kafka.svc.cluster.local:2888:3888;zookeeper2-0.zookeeper2.kafka.svc.cluster.local:2888:3888;zookeeper3-0.zookeeper3.kafka.svc.cluster.local:2888:3888"
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: lead-election
        - containerPort: 3888
          name: zoo-election

