apiVersion: v1
kind: Service
metadata:
  name: zookeeper1
  namespace: kafka
spec:
  ports:
  - port: 2181
    name: client 
  - port: 2888
    name: lead-election
  - port: 3888
    name: zoo-election
  clusterIP: None
  selector:
    app: zookeeper1
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper2
  namespace: kafka
spec:
  ports:
  - port: 2181
    name: client
  - port: 2888
    name: lead-election
  - port: 3888
    name: zoo-election
  clusterIP: None
  selector:
    app: zookeeper2
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper3
  namespace: kafka
spec:
  ports:
  - port: 2181
    name: client
  - port: 2888
    name: lead-election
  - port: 3888
    name: zoo-election
  clusterIP: None
  selector:
    app: zookeeper3
